# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "lanraragi-api"
copyright = "2026, Gustaavv"
author = "Gustaavv"
release = "0.9.81.1"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
]

templates_path = ["_templates"]
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "alabaster"
html_static_path = ["_static"]

# Alabaster's default sidebar blocks, plus coverage.html which links to the
# test coverage reports generated by `make docs.coverage`.
html_sidebars = {
    "**": [
        "about.html",
        "searchfield.html",
        "navigation.html",
        "coverage.html",
        "relations.html",
        "donate.html",
    ]
}


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
