name: Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - ".python-version"
      - "demo.py"
      - "Makefile"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python and uv
        uses: ./.github/actions/python-uv-setup

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Format
        run: make format-check

      - name: Lint
        run: make lint
