name: Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate version number
        run: |
          PY_VERSION=$(grep -oP "(?<=version=['\"])[^'\"]+(?=['\"])" setup.py | head -1)
          TAG=${GITHUB_REF#refs/*/}
          
          if [ "$PY_VERSION" != "$TAG" ]; then
            echo "::error::Tag mismatch! Run tag: $TAG, setup.py version: $PY_VERSION"
            exit 1
          fi
          
          echo "Validation succeeds, version number = $TAG"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: python setup.py bdist_wheel sdist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*